name: build

on: [push]

jobs:
  build:
    name: build and test
    runs-on: [self-hosted]
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        pip${{ matrix.python-version }} install pylint pytest coverage coveralls
        pip${{ matrix.python-version }} install -r requirements.txt
    - name: Linting with pylint
      run: |
        pylint $(git ls-files 'qmcblip/*.py')
    - name: Test with pytest
      run: |
        python${{ matrix.python-version }} -m coverage run -m --source=qmcblip pytest tests
        python${{ matrix.python-version }} -m coverage report
    - name: Coveralls
      run: python${{ matrix.python-version }} -m coveralls --service=github
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
        COVERALLS_FLAG_NAME: python-${{ matrix.python-version }}
        COVERALLS_PARALLEL: true

  finish:
    needs: build
    runs-on: [self-hosted]
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true